version: '3.1'

services:

  zookeeper:
    container_name: zookeeper
    image: confluent/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    build: ./kafka
    links:
     - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -javaagent:/etc/kafka/jmx_prometheus_javaagent.jar=9000:/etc/kafka/prom-jmx-agent-config.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus:/etc/prometheus
    links:
      - kafka

  grafana:
    container_name: grafana
    image: grafana/grafana:5.2.2
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always